import {
  pgTable,
  text,
  serial,
  timestamp,
  jsonb,
  real,
  integer,
  uniqueIndex,
  index,
  vector,
  boolean,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

// Content table: normalized media objects with vector embeddings
export const content = pgTable(
  "content",
  {
    id: serial("id").primaryKey(),
    // Content identification and provenance
    contentType: text("content_type").notNull(), // article, video, image, tweet, instagram_post, etc.
    sourceId: text("source_id").notNull(), // unique ID from source (tweet ID, YouTube video ID, Instagram post ID, etc.)
    sourceType: text("source_type").notNull(), // twitter, youtube, instagram, rss, reddit, etc.
    sourceUrl: text("source_url").notNull(), // original URL/permalink
    crawlTime: timestamp("crawl_time").notNull().defaultNow(),

    // Metadata and content
    title: text("title"),
    description: text("description"),
    content: text("content"), // extracted article text, tweet content, caption, etc.
    author: text("author"),
    publishedAt: timestamp("published_at"),

    // Media assets
    posterUrl: text("poster_url"), // primary image, thumbnail, or video poster
    mediaUrls: jsonb("media_urls"), // array of images/video URLs
    videoLength: integer("video_length"), // in seconds, for YouTube/video content
    youtubeVideoId: text("youtube_video_id"), // extracted from URL

    // Extracted data
    transcript: text("transcript"), // video/podcast transcript if available
    readingTime: integer("reading_time"), // estimated minutes for articles
    wordCount: integer("word_count"),

    // Tagging and categorization
    tags: jsonb("tags").default(sql`'[]'::jsonb`), // array of tag strings
    generatedTags: jsonb("generated_tags").default(sql`'[]'::jsonb`), // tags generated by system
    userGeneratedTags: jsonb("user_generated_tags").default(sql`'[]'::jsonb`), // tags user added

    // Vector embeddings for semantic search
    embedding: vector("embedding", 384), // using Sentence-Transformers dimension
    embeddingModel: text("embedding_model").default("all-MiniLM-L6-v2"),

    // Deduplication tracking
    contentHash: text("content_hash"), // SHA-256 of normalized content for dedup
    isDuplicate: boolean("is_duplicate").default(false),
    originalContentId: integer("original_content_id"), // if duplicate, points to original

    // Collection membership (for Instagram saved collections, etc.)
    collections: jsonb("collections").default(sql`'[]'::jsonb`), // array of collection names/IDs

    // Quality and ranking signals
    sourceQuality: real("source_quality"), // 0-1 score of source reliability
    engagement: jsonb("engagement").default(sql`'{}'::jsonb`), // external engagement metrics
  },
  (table) => ({
    sourceIdIdx: uniqueIndex("content_source_id_idx").on(
      table.sourceType,
      table.sourceId
    ),
    contentHashIdx: uniqueIndex("content_content_hash_idx").on(
      table.contentHash
    ),
    createdIdx: index("content_created_idx").on(table.crawlTime),
    tagsIdx: index("content_tags_idx").on(table.tags),
    embeddingIdx: index("content_embedding_idx").on(table.embedding),
  })
);

// User preferences: tag weights, inclusion/exclusion rules
export const userPreferences = pgTable(
  "user_preferences",
  {
    id: serial("id").primaryKey(),
    userId: text("user_id").notNull(),

    // Tag-based preferences
    tagWeights: jsonb("tag_weights").default(sql`'{}'::jsonb`), // { tag: weight (0-100) }
    focusTags: jsonb("focus_tags").default(sql`'[]'::jsonb`), // tags to prioritize (OR logic)
    mutedTags: jsonb("muted_tags").default(sql`'[]'::jsonb`), // tags to exclude
    requireTags: jsonb("require_tags").default(sql`'[]'::jsonb`), // all must match (AND logic)

    // Source-based preferences
    preferredSources: jsonb("preferred_sources").default(sql`'[]'::jsonb`), // [ instagram, youtube, etc ]
    mutedSources: jsonb("muted_sources").default(sql`'[]'::jsonb`), // sources to exclude

    // Session vs permanent
    isSessionOnly: boolean("is_session_only").default(false), // session-scoped preferences
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (table) => ({
    userIdIdx: index("user_preferences_user_id_idx").on(table.userId),
  })
);

// User feedback: likes, saves, skips, tag edits for learning
export const userFeedback = pgTable(
  "user_feedback",
  {
    id: serial("id").primaryKey(),
    userId: text("user_id").notNull(),
    contentId: integer("content_id").notNull(),

    // Engagement signals
    liked: boolean("liked").default(false),
    saved: boolean("saved").default(false),
    skipped: boolean("skipped").default(false),
    dwellTime: integer("dwell_time"), // seconds spent viewing

    // Tag feedback
    tagsAdded: jsonb("tags_added").default(sql`'[]'::jsonb`), // tags user added
    tagsRemoved: jsonb("tags_removed").default(sql`'[]'::jsonb`), // tags user removed

    // Source feedback
    sourceVisited: boolean("source_visited").default(false),
    collectionAdded: text("collection_added"), // if user saved to collection

    // Metadata
    recordedAt: timestamp("recorded_at").notNull().defaultNow(),
    sessionId: text("session_id"), // for session-scoped analysis
  },
  (table) => ({
    userIdIdx: index("user_feedback_user_id_idx").on(table.userId),
    contentIdIdx: index("user_feedback_content_id_idx").on(table.contentId),
    recordedIdx: index("user_feedback_recorded_idx").on(table.recordedAt),
  })
);

// Ingestion tracking: source adapters, discovery jobs
export const ingestionState = pgTable(
  "ingestion_state",
  {
    id: serial("id").primaryKey(),
    sourceType: text("source_type").notNull(), // twitter, youtube, instagram, rss, etc.
    sourceIdentifier: text("source_identifier").notNull(), // handle, channel ID, feed URL, etc.

    // Pagination state for continuous discovery
    lastCursor: text("last_cursor"), // for API pagination (Twitter next_token, etc)
    lastFetchTime: timestamp("last_fetch_time"),
    itemsDiscoveredTotal: integer("items_discovered_total").default(0),

    // Health tracking
    consecutiveFailures: integer("consecutive_failures").default(0),
    lastErrorMessage: text("last_error_message"),
    isActive: boolean("is_active").default(true),

    // Rate limiting and scheduling
    nextRetryAt: timestamp("next_retry_at"),
    retryBackoffMs: integer("retry_backoff_ms").default(5000),
  },
  (table) => ({
    sourceTypeIdx: index("ingestion_source_type_idx").on(table.sourceType),
    activeIdx: index("ingestion_active_idx").on(table.isActive),
  })
);

export type Content = typeof content.$inferSelect;
export type NewContent = typeof content.$inferInsert;
export type UserPreferences = typeof userPreferences.$inferSelect;
export type NewUserPreferences = typeof userPreferences.$inferInsert;
export type UserFeedback = typeof userFeedback.$inferSelect;
export type NewUserFeedback = typeof userFeedback.$inferInsert;
export type IngestionState = typeof ingestionState.$inferSelect;
export type NewIngestionState = typeof ingestionState.$inferInsert;
